config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present?

    can :create, Post
    can :create, Comment

    can [:destroy], Post, author_id: user.id
    can [:destroy], Comment, user_id: user.id

    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter) if post.has_attribute?(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter) if post.has_attribute?(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates_numericality_of :comments_counter, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :likes_counter, only_integer: true, greater_than_or_equal_to: 0

  after_save :update_posts_counter

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter) if author.has_attribute?(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  validates :name, presence: true
  validates_numericality_of :posts_counter, only_integer: true, greater_than_or_equal_to: 0

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      skip_before_action :verify_authenticity_token

      def index
        @post = Post.find(params[:post_id])
        @comments = @post.comments
        render json: @comments
      end

      def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(comment_params)
        @comment.user = current_user

        if @comment.save
          render json: @comment, status: :created
        else
          render json: { success: false, errors: @comment.errors.full_messages }, status: :unprocessable_entity
        end
      end

      private

      def comment_params
        params.require(:comment).permit(:text)
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        @posts = current_user.posts
        render json: @posts
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post_and_user
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])

    if @comment.destroy
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully deleted.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Error deleting comment.'
    end
  end

  private

  def set_post_and_user
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post_and_user

  def create
    if @post.likes.exists?(user: @user)
      redirect_to user_posts_path(@user), alert: 'You have already liked this post.'
    else
      @like = @post.likes.build(user: @user)

      if @like.save
        redirect_to user_posts_path(@user), notice: 'Post liked successfully.'
      else
        redirect_to user_posts_path(@user), alert: 'Error liking the post.'
      end
    end
  end

  private

  def set_post_and_user
    @user = current_user
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_user

  def index
    @posts = @user.posts.includes(:comments, :likes)
  end

  def show
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @user = User.find_by_id(params[:user_id])

    if @post.destroy
      redirect_to user_posts_path(@user), notice: 'Post was successfully deleted.'
    else
      redirect_to user_posts_path(@user), alert: 'Error deleting post.'
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add New Comment!</h1>
<hr class="col-md-6 mb-5">


<%= form_with(model: @comment, url: user_post_comments_path(@user, @post)) do |form| %>

  <div class="col-md-6 mb-3">
    <%= form.label :text, style: "display: block",class: "fw-bold form-label" %>
    <%= form.text_area :text, class: "form-control", placeholder: "Comment", rows: "3" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Add Comment", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_user_details.html.erb
<div class="user-image-container">
  <img src="<%= user.photo %>" alt="<%= user.name %>">
</div>

<div class="user-details-container">
  <h1><%= user.name %></h1>
  <p class="post-count">Number of posts: <%= user.posts.count %></p>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts/index', media: 'all' %>

<div class="user-show-container">
  <%= render partial: 'user_details', locals: { user: @user } %>
</div>

<div class="user-posts-container">
  <ul>
    <% @posts.each do |post| %>
      <li>
        <h2>
          <%= link_to post.title, user_post_path(@user, post) %>
        </h2>

        <%= "#{post.text}" %>
        <p class="post-metadata">
          <span class="comments-count">Comments: <%= post.comments.count %></span>
          <span class="likes-count">Likes: <%= post.likes.count %></span>
        </p>

        <ul class="comments-list">
          <% post.five_recent_comments.each do |comment| %>
            <li>
              <strong><%= comment.user.name %>:</strong> <%= comment.text %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

<div class="text-center mt-4">
  <%= link_to 'Create New Post', new_user_post_path(user_id: @user), class: 'btn btn-success' %>
</div>

<div class="last-btn pagination">
  <button class="back-link">Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: [@user,@post] do |form| %>
  
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'posts/show' %>

<div class="post-container">
  <h1>
    <% @user.posts.each do |post| %>
      <h4><%= post.title %></h4>
    <% end %>
    <p>Post <%= @user.posts.count %> by <%= @user.name %></p>
  </h1>

  <div class="comments-likes">
    <p>
      <strong>Comments: <%= @post.comments.count %></strong>,
      <strong>Likes: <%= @post.likes.count %></strong>
      <%= form_with(url: user_post_likes_path(@user, @post), method: :post, local: true, class: 'like-form') do |form| %>
        <%= form.submit 'Like', class: 'like-button' %>
      <% end %>
    </p>
  </div>
</div>

<p class="post-text"><%= @post.text %></p>

<% if can?(:destroy, @post) %>
  <%= button_to "Delete Post", user_post_path(@post.author, @post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
<% end %>

<div class="user-comments-container">
  <ul>
  <% @post.comments.each do |comment| %>
    <li>
      <strong><%= comment.user.name %>:</strong> <%= comment.text %>
      <% if can? :destroy, comment %>
      <%= button_to 'Delete Comment', user_post_comment_path(comment.user, comment.post.id, comment), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      <% end %>
    </li>
  <% end %>
  
  </ul>
</div>

<%= link_to 'Back to Posts', user_posts_path(@user), class: 'back-link' %>

<%= link_to 'Add a Comment', new_user_post_comment_path(@user, @post), class: 'add-comment-link' %>

app/views/users/_user_details.html.erb
<div class="user-image-container">
  <img src="<%= @user.photo %>" alt="<%= @user.name %>">
</div>

<div class="user-details-container">
  <h1><%= @user.name %></h1>
  <p class="post-count">Number of Posts: <%= @user.posts.count %></p>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'users/index', media: 'all' %>

<% @users.each do |user| %>
  <div class="home-users">
    <div class="user-photo">
      <img src="<%= user.photo %>" alt="user-photo">
    </div>
    <div class="user-data">
      <%= link_to user.name, user_path(id: user.id), class: 'user-link' %>
      <p class="posts-counter">Number of Posts: <%= user.posts.count %></p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users/show', media: 'all' %>

<div class="user-show-container">
<%= render partial: 'user_details', locals: { user: @user } %>
</div>

<div class="user-bio-container">
  <h2 class="h2-bio">Bio</h2>
  <p><%= @user.bio %></p>
</div>

<div class="user-posts-container">
  <h2>Recent Posts</h2>

  <ul>
    <% @user.three_recent_posts.each do |post| %>
      <li class="posts-container">
        <h3><%= "Post # #{post.id}" %></h3>
        <%= link_to user_post_path(@user, post) do %>
          <h5><%= post.title %></h5>
        <% end %>
        <p class="post-text"><%= post.text %></p>
        <p class="post-metadata">
          <span class="comments-count">Comments: <%= post.comments.count %></span>
          <span class="likes-count">Likes: <%= post.likes.count %></span>
        </p>
      </li>
    <% end %>
  </ul>
</div>

<div class="bottom-button">
  <%= link_to 'See All Posts', user_posts_path(@user), class: 'last-btn' %>
</div>